CREATE DATABASE friends_db;
USE friends_db;

CREATE TABLE friend_list (
  friend_id INTEGER(11) AUTO_INCREMENT NOT NULL,
  friend_name VARCHAR(100) NOT NULL,
  friend_photo_url VARCHAR(1000) NOT NULL,
  q1 INTEGER(11) NOT NULL,
  q2 INTEGER(11) NOT NULL,
  q3 INTEGER(11) NOT NULL,
  q4 INTEGER(11) NOT NULL,
  q5 INTEGER(11) NOT NULL,
  q6 INTEGER(11) NOT NULL,
  q7 INTEGER(11) NOT NULL,
  q8 INTEGER(11) NOT NULL,
  q9 INTEGER(11) NOT NULL,
  q10 INTEGER(11) NOT NULL,
  PRIMARY KEY (friend_id)
);